services:
  - type: web
    name: vidhikbot-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: PYTHON_VERSION=3.11.9

    plan: free
